
server:
  port: 2001
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1001/eureka/
spring:
  application:
    name: eureka_clent
